"""Render the equivalent Python script of a GUI configuration.

The script is a thin wrapper around the public API, built from the same
resolved options the GUI hands to ``build_run_kwargs``: it rebuilds that
Namespace and calls ``build_run_kwargs`` and ``run_scenario`` itself. There
is no separate export mapping, so the script cannot drift from the GUI.

Two kinds of code are produced:

- a *preview* of the current form settings, which is not a run;
- the code of a specific run, rendered from its frozen :class:`RunSpec`,
  including the seed the run actually used when the run confirmed it.

Every value is written as a Python literal via ``repr`` and checked with
``ast.literal_eval``; text that reaches a comment is written through
:func:`_safe`, so no form text can break out into code. The GUI never runs
the generated script.
"""

from __future__ import annotations

import ast
import math
import pathlib
import re
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from .runner import RunSpec, run_outcome, run_stamp

# Options that are paths on this machine. They go into the PATHS block,
# resolved to absolute paths, so they are easy to find and edit.
_PATH_KEYS = ("scenario", "fds_dir", "vis_cache")

# Output files the GUI writes through run.py's apply_outputs. That writer is
# not part of the installed package, so the script does not write them; the
# keys are set to None (build_run_kwargs reads only output_route_cost_history,
# and collect_route_cost_history keeps that history on).
OMITTED_OUTPUT_KEYS = (
    "output_sqlite",
    "output_smoke_history",
    "output_fed_history",
    "output_route_history",
    "output_route_cost_history",
    "export_app_bundle",
)

_PLAIN = re.compile(r"[\w.+:@/-]*")


class ExportError(ValueError):
    """The configuration holds a value that cannot be written as a literal."""


@dataclass(frozen=True)
class ExportedScript:
    """A rendered script and the name to download it under."""

    code: str
    filename: str
    options: dict[str, Any]


def _safe(text: Any) -> str:
    """Return *text* for a comment: plain as is, anything else as ``repr``.

    ``repr`` escapes newlines, carriage returns and every other line or
    paragraph separator, so a hostile name cannot end the comment line.
    """
    s = str(text)
    return s if _PLAIN.fullmatch(s) else repr(s)


def _literal(key: str, value: Any) -> str:
    """Return ``repr(value)``, refusing anything that is not a plain literal."""
    if value is not None and not isinstance(value, (bool, int, float, str)):
        raise ExportError(f"{key}: {type(value).__name__} is not exportable")
    if isinstance(value, float) and not math.isfinite(value):
        raise ExportError(f"{key}: {value!r} is not a finite number")
    text = repr(value)
    if ast.literal_eval(text) != value:  # pragma: no cover - defensive
        raise ExportError(f"{key}: {value!r} does not round-trip")
    return text


def _abs_path(value: Any) -> str | None:
    """Resolve a path option as the GUI process sees it, or keep None."""
    if value is None or str(value).strip() == "":
        return None
    return str(pathlib.Path(str(value)).expanduser().resolve())


def _stem(scenario_name: str) -> str:
    """A filename-safe stem for the scenario."""
    stem = re.sub(r"[^A-Za-z0-9_-]+", "_", scenario_name.replace(".json", ""))
    return stem.strip("_") or "scenario"


def export_options(opts: Mapping[str, Any], seed: Any) -> dict[str, Any]:
    """The non-path options the script passes, in a stable order."""
    options = {"seed": seed}
    for key in sorted(opts):
        if key in _PATH_KEYS or key == "seed":
            continue
        options[key] = None if key in OMITTED_OUTPUT_KEYS else opts[key]
    return options


def _header(lines: list[str], version: Any, commit: Any, dirty: Any) -> list[str]:
    """The comment header shared by both kinds of script."""
    commit_text = "commit not recorded" if not commit else f"commit {_safe(commit)}"
    if dirty:
        commit_text += " (with uncommitted changes)"
    return [
        "# Generated by the pyFDS-Evac GUI.",
        f"# pyfds-evac {_safe(version or 'version not recorded')}, {commit_text}.",
        *lines,
        "#",
        "# Needs the pyfds-evac version above, installed the same way as the GUI",
        "# (for example `uv sync` in the repository). The GUI extra is not needed.",
        "# This file contains code only: the scenario folder and FDS results are",
        "# not included. Copy them to the other machine and edit PATHS below.",
        "# Results can differ from the GUI run, even with the same seed, with",
        "# other versions or on other platforms.",
        "# Omitted: the GUI's output files (CSV histories, app bundle), whose",
        "# writer lives in run.py outside the package, and the progress callback,",
        "# which only drives the GUI. The trajectory and its manifest are copied",
        "# to OUTPUT_DIR.",
    ]


def _seed_comment(kind: str, spec: RunSpec | None, seed: Any, baseseed: Any) -> str:
    """Why the script's seed has the value it has."""
    if kind == "run" and spec is not None and spec.seed_used is not None:
        return f"  # seed used by run #{spec.run_id}"
    if kind == "run" and seed is None:
        return "  # seed not recorded for this run; None = the scenario's baseSeed"
    if kind == "run":
        return "  # seed submitted; the seed used was not recorded"
    if seed is None:
        return f"  # None = the scenario's baseSeed ({_safe(baseseed)})"
    return ""


def _body(
    paths: dict[str, str | None],
    output_dir: str,
    options: dict[str, Any],
    seed_comment: str,
) -> list[str]:
    """Imports, PATHS, settings, the run and the result check."""
    lines = [
        "",
        "import argparse",
        "import pathlib",
        "import shutil",
        "",
        "from pyfds_evac.core import load_scenario, run_scenario",
        "from pyfds_evac.core.manifest import manifest_path_for",
        "from pyfds_evac.core.run_config import build_run_kwargs",
        "",
        "# PATHS: from the computer that ran the GUI. Edit them on another machine.",
        f"SCENARIO = {_literal('scenario', paths['scenario'])}",
        f"FDS_DIR = {_literal('fds_dir', paths['fds_dir'])}",
        f"VIS_CACHE = {_literal('vis_cache', paths['vis_cache'])}",
        "# A new folder: the script never overwrites the GUI run's files.",
        f"OUTPUT_DIR = pathlib.Path({_literal('output_dir', output_dir)})",
        "",
        "# Settings: the resolved configuration the GUI passes to build_run_kwargs.",
        "OPTIONS = {",
    ]
    for key, value in options.items():
        comment = seed_comment if key == "seed" else ""
        lines.append(f"    {_literal(key, key)}: {_literal(key, value)},{comment}")
    lines += [
        "}",
        "",
        "opts = argparse.Namespace(",
        "    **OPTIONS,",
        "    scenario=SCENARIO,",
        "    fds_dir=FDS_DIR,",
        "    vis_cache=VIS_CACHE,",
        ")",
        "",
        "scenario = load_scenario(SCENARIO)",
        "run_kwargs = build_run_kwargs(scenario, opts, log=print)",
        "result = run_scenario(scenario, **run_kwargs)",
        "",
        "if result.agents_remaining == 0:",
        "    print(",
        '        f"Simulation finished in {result.evacuation_time:.2f} s "',
        '        f"({result.agents_evacuated}/{result.total_agents} evacuated)."',
        "    )",
        "else:",
        "    print(",
        '        f"Simulation stopped after {result.evacuation_time:.2f} s "',
        '        f"({result.agents_evacuated}/{result.total_agents} evacuated, "',
        '        f"{result.agents_remaining} remaining)."',
        "    )",
        "",
        "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)",
        "if result.sqlite_file:",
        '    trajectory = OUTPUT_DIR / "trajectory.sqlite"',
        "    shutil.copy2(result.sqlite_file, trajectory)",
        '    print(f"Trajectory SQLite: {trajectory.resolve()}")',
        "    if result.manifest_file:",
        "        shutil.copy2(result.manifest_file, manifest_path_for(trajectory))",
        "result.cleanup()  # remove the temporary copies run_scenario wrote",
        "",
    ]
    return lines


def _render(
    header: list[str],
    opts: Mapping[str, Any],
    seed: Any,
    seed_comment: str,
    output_dir: str,
    filename: str,
) -> ExportedScript:
    paths = {key: _abs_path(opts.get(key)) for key in _PATH_KEYS}
    options = export_options(opts, seed)
    code = "\n".join([*header, *_body(paths, output_dir, options, seed_comment)])
    ast.parse(code)  # a rendering bug must never reach the user as code
    return ExportedScript(code=code, filename=filename, options=options)


def preview_script(
    opts: Mapping[str, Any],
    scenario_name: str,
    scenario_path: str,
    *,
    version: Any,
    commit: Any,
    dirty: Any,
    baseseed: Any,
) -> ExportedScript:
    """Script for the current form settings. This is not a run."""
    stem = _stem(scenario_name)
    header = _header(
        [
            "# Preview of form settings, not a run.",
            f"# Scenario: {_safe(scenario_name)}",
        ],
        version,
        commit,
        dirty,
    )
    seed = opts.get("seed")
    return _render(
        header,
        {**opts, "scenario": scenario_path},
        seed,
        _seed_comment("preview", None, seed, baseseed),
        f"pyfds_evac_{stem}_preview_output",
        f"pyfds_evac_{stem}_preview.py",
    )


def run_script(spec: RunSpec) -> ExportedScript:
    """Script for the run recorded in *spec*, never the live form."""
    stem = _stem(spec.scenario_name)
    header = _header(
        [
            f"# Run #{spec.run_id}, started {_safe(spec.started_at)}.",
            f"# Scenario: {_safe(spec.scenario_name)}",
        ],
        spec.pyfds_evac_version,
        spec.git_commit,
        spec.git_dirty,
    )
    seed = spec.seed_used if spec.seed_used is not None else spec.opts.get("seed")
    # Run numbers restart with every GUI session; the start time does not.
    name = f"pyfds_evac_{stem}_run{spec.run_id}_{run_stamp(spec.started_at)}"
    opts = dict(spec.opts)
    opts["scenario"] = spec.scenario_path
    return _render(
        header,
        opts,
        seed,
        _seed_comment("run", spec, spec.opts.get("seed"), None),
        f"{name}_output",
        f"{name}.py",
    )


def run_status(spec: RunSpec) -> str:
    """One-line outcome of a run, worded as the results view words it."""
    if spec.status == "error":
        return "failed"
    if spec.status == "cancelled":
        return "cancelled"
    if spec.status != "done" or spec.agents_remaining is None:
        return "not recorded"
    outcome = run_outcome(
        spec.all_evacuated,
        spec.agents_remaining,
        spec.total_agents,
        spec.evacuation_time,
        spec.time_limit,
    )
    if outcome.complete:
        return (
            f"{outcome.label} ({spec.agents_evacuated}/{spec.total_agents}), "
            f"evacuation time {spec.evacuation_time:.2f} s"
        )
    return f"{outcome.label}, simulated time {spec.evacuation_time:.2f} s"
