"""Render the equivalent Python script of a GUI configuration.

The script is a thin wrapper around the public API, built from the same
resolved options the GUI hands to ``build_run_kwargs``: it rebuilds that
Namespace and calls ``build_run_kwargs`` and ``run_scenario`` itself. There
is no separate export mapping, so the script cannot drift from the GUI.

Two kinds of code are produced:

- a *preview* of the current form settings, which is not a run;
- the code of a specific run, rendered from its frozen :class:`RunSpec`,
  including the seed the run actually used when the run confirmed it.

Every value is written as a Python literal via ``repr`` and checked with
``ast.literal_eval``; text that reaches a comment is written through
:func:`_safe`, so no form text can break out into code. The GUI never runs
the generated script.
"""

from __future__ import annotations

import ast
import re
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

# The literal checks and the script body are shared with
# pyfds_evac.config.python_script; the names stay importable from here.
from pyfds_evac.config.script import (  # noqa: F401
    _PATH_KEYS,
    OMITTED_OUTPUT_KEYS,
    ExportError,
    _abs_path,
    _body,
    _literal,
    _safe,
    export_options,
)

from .runner import RunSpec, run_outcome, run_stamp


@dataclass(frozen=True)
class ExportedScript:
    """A rendered script and the name to download it under."""

    code: str
    filename: str
    options: dict[str, Any]


def _stem(scenario_name: str) -> str:
    """A filename-safe stem for the scenario."""
    stem = re.sub(r"[^A-Za-z0-9_-]+", "_", scenario_name.replace(".json", ""))
    return stem.strip("_") or "scenario"


def _header(lines: list[str], version: Any, commit: Any, dirty: Any) -> list[str]:
    """The comment header shared by both kinds of script."""
    commit_text = "commit not recorded" if not commit else f"commit {_safe(commit)}"
    if dirty:
        commit_text += " (with uncommitted changes)"
    return [
        "# Generated by the pyFDS-Evac GUI.",
        f"# pyfds-evac {_safe(version or 'version not recorded')}, {commit_text}.",
        *lines,
        "#",
        "# Needs the pyfds-evac version above, installed the same way as the GUI",
        "# (for example `uv sync` in the repository). The GUI extra is not needed.",
        "# This file contains code only: the scenario folder and FDS results are",
        "# not included. Copy them to the other machine and edit PATHS below.",
        "# Results can differ from the GUI run, even with the same seed, with",
        "# other versions or on other platforms.",
        "# Omitted: the GUI's output files (CSV histories, app bundle), whose",
        "# writer lives in run.py outside the package, and the progress callback,",
        "# which only drives the GUI. The trajectory and its manifest are copied",
        "# to OUTPUT_DIR.",
    ]


def _seed_comment(kind: str, spec: RunSpec | None, seed: Any, baseseed: Any) -> str:
    """Why the script's seed has the value it has."""
    if kind == "run" and spec is not None and spec.seed_used is not None:
        return f"  # seed used by run #{spec.run_id}"
    if kind == "run" and seed is None:
        return "  # seed not recorded for this run; None = the scenario's baseSeed"
    if kind == "run":
        return "  # seed submitted; the seed used was not recorded"
    if seed is None:
        return f"  # None = the scenario's baseSeed ({_safe(baseseed)})"
    return ""


def _render(
    header: list[str],
    opts: Mapping[str, Any],
    seed: Any,
    seed_comment: str,
    output_dir: str,
    filename: str,
) -> ExportedScript:
    paths = {key: _abs_path(opts.get(key)) for key in _PATH_KEYS}
    options = export_options(opts, seed)
    code = "\n".join([*header, *_body(paths, output_dir, options, seed_comment)])
    ast.parse(code)  # a rendering bug must never reach the user as code
    return ExportedScript(code=code, filename=filename, options=options)


def preview_script(
    opts: Mapping[str, Any],
    scenario_name: str,
    scenario_path: str,
    *,
    version: Any,
    commit: Any,
    dirty: Any,
    baseseed: Any,
) -> ExportedScript:
    """Script for the current form settings. This is not a run."""
    stem = _stem(scenario_name)
    header = _header(
        [
            "# Preview of form settings, not a run.",
            f"# Scenario: {_safe(scenario_name)}",
        ],
        version,
        commit,
        dirty,
    )
    seed = opts.get("seed")
    return _render(
        header,
        {**opts, "scenario": scenario_path},
        seed,
        _seed_comment("preview", None, seed, baseseed),
        f"pyfds_evac_{stem}_preview_output",
        f"pyfds_evac_{stem}_preview.py",
    )


def run_script(spec: RunSpec) -> ExportedScript:
    """Script for the run recorded in *spec*, never the live form."""
    stem = _stem(spec.scenario_name)
    header = _header(
        [
            f"# Run #{spec.run_id}, started {_safe(spec.started_at)}.",
            f"# Scenario: {_safe(spec.scenario_name)}",
        ],
        spec.pyfds_evac_version,
        spec.git_commit,
        spec.git_dirty,
    )
    seed = spec.seed_used if spec.seed_used is not None else spec.opts.get("seed")
    # Run numbers restart with every GUI session; the start time does not.
    name = f"pyfds_evac_{stem}_run{spec.run_id}_{run_stamp(spec.started_at)}"
    opts = dict(spec.opts)
    opts["scenario"] = spec.scenario_path
    return _render(
        header,
        opts,
        seed,
        _seed_comment("run", spec, spec.opts.get("seed"), None),
        f"{name}_output",
        f"{name}.py",
    )


def run_status(spec: RunSpec) -> str:
    """One-line outcome of a run, worded as the results view words it."""
    if spec.status == "error":
        return "failed"
    if spec.status == "cancelled":
        return "cancelled"
    if spec.status != "done" or spec.agents_remaining is None:
        return "not recorded"
    outcome = run_outcome(
        spec.completion, spec.agents_remaining, spec.agents_not_spawned
    )
    if spec.incapacitation_modelled and spec.agents_incapacitated is not None:
        incap = f", {spec.agents_incapacitated} incapacitated"
    else:
        incap = ", incapacitation not modelled"
    if outcome.complete:
        return (
            f"{outcome.label} ({spec.agents_evacuated}/{spec.total_agents}), "
            f"evacuation time {spec.evacuation_time:.2f} s{incap}"
        )
    return f"{outcome.label}, simulated time {spec.evacuation_time:.2f} s{incap}"
