name: fds-evac

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  fds-evac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install --upgrade uv
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Lint with Ruff        
        run: uv run ruff -- .
      
